#%RAML 1.0 NamedExample
value:
-
  dni: 41736372
  name: Ignacio
  surname: Fiori
  gender: M
  city: Buenos Aires
  date_of_birth: 1999-02-11
  enabled?: true
-
  dni: 48678202
  name: Courtney 
  surname: Williams
  gender: F
  city: Cordoba
  date_of_birth: 1997-11-13
  enabled?: true
  